
FROM python:3.9-slim

WORKDIR /app

COPY ./databridge ./databridge
COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Configuração de porta
EXPOSE 8000

# Comando para iniciar a aplicação
CMD ["uvicorn", "databridge.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
